services:
  - type: web
    name: toi-moi
    runtime: docker
    region: fra
    plan: free
    dockerfile: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /index.html
